name       : haskell-base16-bytestring
version    : 0.1.1.6
release    : 1
source     :
    - http://hackage.haskell.org/package/base16-bytestring-0.1.1.6/base16-bytestring-0.1.1.6.tar.gz : 5afe65a152c5418f5f4e3579a5e0d5ca19c279dc9bf31c1a371ccbe84705c449
license    : BSD-3-Clause
component  : programming
summary    : Fast base16 (hex) encoding and decoding for ByteStrings
description: |
    Fast base16 (hex) encoding and decoding for ByteStrings
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 base16-bytestring-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/base16-bytestring-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/base16-bytestring-$version/*.a
