name       : haskell-base16-bytestring
version    : 1.0.2.0
release    : 7
source     :
    - http://hackage.haskell.org/package/base16-bytestring-1.0.2.0/base16-bytestring-1.0.2.0.tar.gz : 1d5a91143ef0e22157536093ec8e59d226a68220ec89378d5dcaeea86472c784
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast base16 (hex) encoding and decoding for ByteStrings
description: |
    Fast base16 (hex) encoding and decoding for ByteStrings
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
